# Generated by Django 4.2.26 on 2025-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_job_salary_range'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['recruiter'], name='application_recruit_d42637_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='application_job_typ_0f2ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='application_locatio_9f1c90_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='application_deadlin_7fffc9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='application_created_c48f79_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'location'], name='application_title_3ee474_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerapplication',
            index=models.Index(fields=['job'], name='application_job_id_0b574a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerapplication',
            index=models.Index(fields=['applicant'], name='application_applica_10a2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerapplication',
            index=models.Index(fields=['status'], name='application_status_b6d817_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerapplication',
            index=models.Index(fields=['-applied_at'], name='application_applied_fe0b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseekerapplication',
            index=models.Index(fields=['job', 'status'], name='application_job_id_0f1e58_idx'),
        ),
    ]
