# Generated by Django 4.2.26 on 2025-12-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('applications', '0003_job_application_recruit_d42637_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('interview', 'Interview'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('other', 'Other')], default='interview', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='jobseekerapplication',
            name='application_job_id_0f1e58_idx',
        ),
        migrations.AlterField(
            model_name='jobseekerapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='profiles.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='profiles.recruiterprofile'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recruiter'], name='application_recruit_34a583_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='application_event_t_c0bf5f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['date'], name='application_date_dfe0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['-created_at'], name='application_created_b318e0_idx'),
        ),
    ]
