# Generated by Django 4.2.26 on 2025-12-16 12:47

import applications.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_calendarevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(validators=[applications.validators.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='jobseekerapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/letters/', validators=[applications.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobseekerapplication',
            name='resume',
            field=models.FileField(upload_to='applications/resumes/', validators=[applications.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
